# Generated by Django 5.1.6 on 2025-02-28 15:17

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категории книг',
                'verbose_name_plural': 'Категории книг',
            },
        ),
        migrations.CreateModel(
            name='CategoryForCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='OurCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'наш курс',
                'verbose_name_plural': 'Наши курсы',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='фио')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('rating', models.IntegerField(default=1, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название соцсети')),
                ('link', models.CharField(max_length=255, verbose_name='ссылка')),
                ('image', models.CharField(max_length=255, verbose_name='ссылка на лого')),
            ],
            options={
                'verbose_name': 'Соц.сеть',
                'verbose_name_plural': 'Соц.сеть',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('price', models.CharField(max_length=10, verbose_name='Стоимость')),
                ('img', models.ImageField(blank=True, upload_to='images/')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('but', models.CharField(max_length=50, verbose_name='Название кнопки')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.categoryforcourses', verbose_name='категории')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя фамилие')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фото ава')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('description', ckeditor.fields.RichTextField()),
                ('reviews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.reviews', verbose_name='Отзыв')),
                ('social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.sociallinks', verbose_name='Социальные сети')),
            ],
            options={
                'verbose_name': 'Инструкторы',
                'verbose_name_plural': 'Инструкторы',
            },
        ),
        migrations.CreateModel(
            name='CoursePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('count_lections', models.CharField(help_text='12 лекции', max_length=100, verbose_name='Количество лекции')),
                ('hours', models.CharField(max_length=20, verbose_name='Сколько часов')),
                ('description', ckeditor.fields.RichTextField()),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.instructors', verbose_name='Инструкторы')),
                ('reviews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.reviews', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Курсы',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('author', models.CharField(max_length=100, verbose_name='Имя Автора')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('Page_Count', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('Word_Count', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.categorybook', verbose_name='категория')),
                ('reviews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.reviews', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
