# Generated by Django 5.1.6 on 2025-02-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursepage',
            options={'verbose_name': 'курсы страница', 'verbose_name_plural': 'курсы страница'},
        ),
    ]
