# Generated by Django 5.1.6 on 2025-03-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_coursepage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='цена'),
        ),
    ]
