# Generated by Django 5.1.6 on 2025-02-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_courses_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'наш курс',
                'verbose_name_plural': 'Наши курсы',
            },
        ),
    ]
