# Generated by Django 5.1.6 on 2025-03-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_coursepage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
