# Generated by Django 5.1.6 on 2025-03-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_books_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categorybook',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='Page_Count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='books',
            name='Word_Count',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Количество слов'),
        ),
    ]
