# Generated by Django 5.1.6 on 2025-03-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_books_slug_categorybook_slug_alter_books_page_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='instructors',
            field=models.ManyToManyField(to='project.instructors', verbose_name='Инструкторы'),
        ),
        migrations.RemoveField(
            model_name='instructors',
            name='social',
        ),
        migrations.AddField(
            model_name='instructors',
            name='social',
            field=models.ManyToManyField(blank=True, null=True, to='project.sociallinks', verbose_name='Социальные сети'),
        ),
    ]
