# Generated by Django 5.1.6 on 2025-03-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_sociallinks_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='images/', verbose_name='Логотип')),
                ('numder', models.CharField(help_text='+996 554977013', max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(help_text='courses_kg@gmail.com', max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'данные',
                'verbose_name_plural': 'Данные',
            },
        ),
    ]
