# Generated by Django 5.1.6 on 2025-03-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='numder',
            new_name='phone',
        ),
    ]
