# Generated by Django 5.1.6 on 2025-03-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cound_reviews',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='количество комментариев'),
        ),
        migrations.AddField(
            model_name='blog',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='project.reviews', verbose_name='коментарии'),
        ),
    ]
