# Generated by Django 5.1.6 on 2025-03-23 15:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_data_address_data_email2_data_phone2_alter_data_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='cound_reviews',
            new_name='cound_comments',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='reviews',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project.blog', verbose_name='Блог')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='ReplyComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='project.blog', verbose_name='Блог')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project.comments', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Ответный комментарий',
                'verbose_name_plural': 'ответнные комментарии',
            },
        ),
    ]
