# Generated by Django 5.1.6 on 2025-03-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_comments_avatar_replycomments_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='replycomments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
