# Generated by Django 5.1.6 on 2025-03-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_comments_date_replycomments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(blank=True, help_text='courses_kg@gmail.com', max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='replycomments',
            name='email',
            field=models.EmailField(blank=True, help_text='courses_kg@gmail.com', max_length=100, null=True, verbose_name='Email'),
        ),
    ]
