# Generated by Django 5.1.6 on 2025-03-26 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_data_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='project.comments', verbose_name='Блог'),
        ),
        migrations.DeleteModel(
            name='ReplyComments',
        ),
    ]
