# Generated by Django 5.1.6 on 2025-03-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_comments_parent_delete_replycomments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryForCourses',
            new_name='CategoryCourses',
        ),
    ]
